version: "3.9"
name: nodewave-docker-compose
services:
  postgres:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_DB: "nodewave"
      POSTGRES_PASSWORD: "nodewave"
      POSTGRES_USER: "nwpostgres"
      PGUSER: "nwpostgres"
      PGDATA: /var/lib/postgresql/data/nodewave
    volumes:
      - nodewave:/var/lib/postgresql/data/nodewave
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "nodewave"
      RABBITMQ_DEFAULT_PASS: "nodewave123"
    ports:
      - "5674:5672"
      - "15674:15672"

  redis:
    image: redis:latest
    container_name: redis-nodewave
    ports:
      - "6379:6379"
    volumes:
      - redis_data_nodewave:/data
    command: redis-server --appendonly yes --requirepass localredis

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-nodewave
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=localredis
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  nodewave:
    driver: local
  redis_data_nodewave:
    driver: local