# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check Build On PR To Deployment Branch

on:
    pull_request:
        branches:
            - develop
            - staging
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: "postgres"
                env:
                    POSTGRES_PASSWORD: devpassword
                    POSTGRES_USER: dev
                    POSTGRES_DB: indorajdoc
                ports:
                    - 5432:5432
        steps:
            # Downloads a copy of the code in your repository before running CI tests
            - name: Check out repository code
              uses: actions/checkout@v4

            # Performs a clean installation of all dependencies in the `package.json` file
            # For more information, see https://docs.npmjs.com/cli/ci.html
            - name: Install Bun
              run: npm install -g bun
            - name: Install dependencies
              run: bun install
            #Performs Unit Testing
            - name: Run DB Migration
              run: bun prisma migrate dev --name ciTestMigration
              env:
                  DATABASE_URL: "postgres://dev:devpassword@127.0.0.1:5432/indorajdoc?schema=public"
            - name: Run Build
              run: bun run build
